### ISSUE TITLE
Truncate reply to size expected by client

### ISSUE THREAD

**Issue by wanesoft** [AdguardTeam/DnsLibs#103]

**Comment by ngorskikh** [comment]
Btw, we should also rethink atomatic TCP retries: if the upstream response is truncated, we should NOT automatically retry over TCP, since we would truncate the upstream response received over TCP anyway when replying to the client.
Instead, when we receive a request over TCP, we should skip sending a UDP request to the upstream server (if UDP is an option), and skip truncating the response.

**Comment by sfionov** [comment]
Automatic TCP retry will work anyway - TCP client retry will just return cache entry.

But we definitely need some flag for DnsProxy.exchange(byte[]) to tell if this is request over TCP (to force TCP for plain upstream and not to truncate replies).
