### ISSUE TITLE
DNS unblock rule surpassed by block rule

### ISSUE THREAD

**Issue by AleksandrShulgin** [AdguardTeam/DnsLibs#126]
### Precondition

block rule:
||www.reddit.com^
unblock rule:
@@|reddit.com^$important

### Steps to reproduce
Visit www.reddit.com

### Expected behavior

www.reddit.com loads 

### Actual behavior

www.reddit.com is blocked

### Fearful expectation:
This problem is relevant for all `.com` domains

### Your environment

AdGuard 7.7 Windows

**Comment by sfionov** [comment]
Hello.
Task doesn't describe what do you want to do.
If you want to block anything but www.reddit.com, then valid pair or rules are:
```
||reddit.com^
@@||www.reddit.com^$important
```

**Comment by privacy-advo** [comment]
Well sorry, then going back:

**Precondition:**
Energized Social is used and ||reddit.com^ is an entry. 

**Desired behavior:**
**One** rule which unblocks www.reddit.com & reddit.com which is not  @@||reddit.com^$important, as this one unblocks all subdomains.

That's why I asked how to avoid such a painful work of doubled entries for unblocking domains.
