### ISSUE TITLE
`$dnsrewrite` priority issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/DnsLibs#171]
### Actual behavior

`$dnsrewrite` cannot overryde a regular blocking rule.

* The rule which I tried to override

`||d192r5l88wrng7.cloudfront.net^`

* The rule, used to override the blocking rule:

`||d192r5l88wrng7.cloudfront.net^$dnsrewrite=cloudfront.net`

or/and

`||d192r5l88wrng7.cloudfront.net^$dnsrewrite=cloudfront.net,important`

<details>
<summary>Windows</summary>

![image](https://user-images.githubusercontent.com/8361299/209995674-c56db3d4-f964-41ad-870f-239fced9af29.png)

![image](https://user-images.githubusercontent.com/8361299/209995227-ee6ef134-835f-4b2d-9f1f-b35b8d3f85b6.png)

</details>

<details>
<summary>Android</summary>

![image](https://user-images.githubusercontent.com/8361299/209995290-85cc1863-323d-4d8c-8fc8-fa1c238091e3.png)

</details>

### Expected behavior

`$dnsrewrite` must have a higher priority, than a basic rule: https://adguard-dns.io/kb/general/dns-filtering-syntax/#dnsrewrite

AdGuard for Windows 7.12 n5
AdGuard for Android 4 nightly (CL 1.10.177, DnsLibs 2.0.66)

**Comment by ngorskikh** [comment]
I've tried to reproduce this. `$dnsrewrite` correctly overrides the basic rule. However, looking at the screenshots, it's probable that REFUSED responses are due to CNAME blocking (i.e. matching CNAME from response against the filters). When a CNAME is matched against the filters, we set the (imaginary) query type to `CNAME`, and `$dnsrewrite=example.org` doesn't match, seemingly by design: 
![image](https://user-images.githubusercontent.com/57908117/211798090-0a31ab5e-ef1d-4dda-8add-fb0e83c59588.png)
@sxgunchenko @ameshkov discuss?

**Comment by ameshkov** [comment]
Why does it go through response filtering when a `$dnsrewrite` rule is applied?

**Comment by ameshkov** [comment]
The point is that if we already applied a `$dnsrewrite` rule, we should not filter response

**Comment by ngorskikh** [comment]
We don't :)

**Comment by ameshkov** [comment]
I don't get the explanation then.

`||d192r5l88wrng7.cloudfront.net^$dnsrewrite=cloudfront.net` is applied to a query.
How can it be blocked due to CNAME blocking if responses are not filtered?

**Comment by ngorskikh** [comment]
Looks like I've overthought this. Those REFUSED responses are probably to `HTTPS` (or anything other than A or AAAA) queries. That is why `$dnsrewrite` is not applied.
