### ISSUE TITLE
Add DoQ support in DNS stamps

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/DnsLibs#84]
The problem is that DNS stamps spec doesn't support this, so type code is unknown.

**Comment by EntropySmoke** [comment]
Slightly Off-topic:
**What are the exact SDNS stamps for AdGuard DoQ and DoH using new IP addreses (94.140.15.15 and 94.140.15.15)?** Are stamps provided somewhere in AdGuard AdBlocker? Do options like "No Log" and "Unfiltered" from DNSCrypt.info SDNS generator actually make a difference? 

For example, the following 2 SDNS addresses are for AdGuard DoH, but the top one is generated without "No Logs" option and the bottom one is generated with "No Logs" option. Are they actually different? Would using top one result in creation of logs?
sdns://AgEAAAAAAAAADDk0LjE0MC4xNC4xNAAPZG5zLmFkZ3VhcmQuY29tCi9kbnMtcXVlcnk
sdns://AgMAAAAAAAAADDk0LjE0MC4xNC4xNAAPZG5zLmFkZ3VhcmQuY29tCi9kbnMtcXVlcnk
AFAIK AdGuard doesn't keep logs

Somewhat Off-Topic:
Do you plan on making DoQ resolve over UDP Port 443 instead of UDP port 784 in the future? One of the reasons DoH is becoming popular is because it uses TCP port 443 that is also used by HTTPS. QUIC uses UDP port 443 and it makes the most sense to make DoQ use UDP port 443.
